version: '3'

name: openresty_standalone

services:
  openresty:
    build:
      context: ./config
      args:
        - RESTY_IMAGE_BASE=${RESTY_IMAGE_BASE}
        - RESTY_IMAGE_TAG=${RESTY_IMAGE_TAG}
        - RESTY_VERSION=${RESTY_VERSION}
        - RESTY_PREFIX=${RESTY_PREFIX}
        - RESTY_DEPS_PREFIX=${RESTY_DEPS_PREFIX}
        - RESTY_J=${RESTY_J}
    image: "zxk175/openresty-alpine:${RESTY_VERSION}"


