version: '3'

name: mysql_standalone

networks:
  well:
    external: true

services:
  mysql_standalone:
    image: mysql:5.7.40
    container_name: mysql_standalone
    privileged: true
    restart: always
    networks:
      - well
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./config/init:/docker-entrypoint-initdb.d
      - ./node/data:/var/lib/mysql
      - ./node/logs:/var/log/mysql
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
