version: '3'

networks:
  redis:
    external: true

services:
  redis1:
    image: redis:5.0.14-alpine3.15
    container_name: redis1
    restart: always
    volumes:
    - ./node/node1/conf/:/etc/redis/
    - ./node/node1/data:/data
    environment:
    - TZ=Asia/Shanghai
    - LANG=en_US.UTF-8
    ports:
      - '7001:6379'
      - '17001:16379'
    command: ["redis-server", "/etc/redis/redis.conf"]
    privileged: true
    networks:
      - redis

  redis2:
    image: redis:5.0.14-alpine3.15
    container_name: redis2
    restart: always
    volumes:
    - ./node/node2/conf/:/etc/redis/
    - ./node/node2/data:/data
    environment:
    - TZ=Asia/Shanghai
    - LANG=en_US.UTF-8
    ports:
      - '7002:6379'
      - '17002:16379'
    command: ["redis-server", "/etc/redis/redis.conf"]
    privileged: true
    networks:
      - redis

  redis3:
    image: redis:5.0.14-alpine3.15
    container_name: redis3
    restart: always
    volumes:
    - ./node/node3/conf/:/etc/redis/
    - ./node/node3/data:/data
    environment:
    - TZ=Asia/Shanghai
    - LANG=en_US.UTF-8
    ports:
      - '7003:6379'
      - '17003:16379'
    command: ["redis-server", "/etc/redis/redis.conf"]
    privileged: true
    networks:
      - redis
