version: '3'

name: postgres_standalone

networks:
  well:
    external: true

services:
  postgres_standalone:
    image: postgres:12.10-alpine3.15
    container_name: postgres_standalone
    privileged: true
    restart: always
    networks:
      - well
    volumes:
      - ./node/data:/var/lib/postgresql/data
      - ./node/logs:/var/lib/postgresql/data/log
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxk123456
    ports:
      - '5432:5432'
