server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    type: nacos
    nacos:
      server-addr: 172.30.0.1:8848
      namespace: 5aa1df41-2aa4-4707-b494-fe1d39ebb2ed
      group: SEATA_GROUP
      username: nacos
      password: nacos1
      data-id: seata.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 172.30.0.1:8848
      group: SEATA_GROUP
      namespace: 5aa1df41-2aa4-4707-b494-fe1d39ebb2ed
      cluster: default
      username: nacos
      password: nacos
  store:
    mode: db
    session:
      mode: db
    lock:
      mode: db
  server:
    service-port: 8091
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login
