version: '3'

name: nacos_standalone_mysql

networks:
  well:
    external: true

services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos_standalone_mysql
    restart: on-failure
    networks:
      - well
    env_file:
      - ./nacos.env
    volumes:
      - ./config/application.properties:/home/nacos/conf/application.properties
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
