version: '3'

name: nacos_standalone_mysql

networks:
  well:
    external: true

services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos_standalone_mysql
    privileged: true
    restart: on-failure
    networks:
      - well
    env_file:
      - ./env/custom-application-config.env
    volumes:
      - ./logs/:/home/nacos/logs
      - ./init/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
