version: '3'

networks:
  well:
    external: true

services:
  postgres:
    image: postgres:12.10-alpine3.15
    container_name: postgres
    privileged: true
    restart: always
    networks:
      - well
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 175745
    ports:
      - '5432:5432'
