version: '3'

name: seata_standalone

networks:
  well:
    external: true

services:
  # seata-temp:
  #   image: seataio/seata-server:1.6.1
  #   container_name: seata_standalone
  #   networks:
  #     - well
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - STORE_MODE=file
  #     - SEATA_PORT=8091
  #   ports:
  #     - "7091:7091"
  #     - "8091:8091"

  seata:
    image: seataio/seata-server:1.6.1
    hostname: seata_standalone
    container_name: seata_standalone
    networks:
      - well
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/application.yml:/seata-server/resources/application.yml
      - ./data/sessionStore:/seata-server/sessionStore
      - ./data/logs:/root/logs/seata
    ports:
      - "7091:7091"
      - "8091:8091"
