version: '3'

name: seata_standalone

networks:
  well:
    external: true

services:
  seata-temp:
    image: seataio/seata-server:1.6.1
    hostname: seata_standalone
    container_name: seata_standalone
    privileged: true
    restart: on-failure
    networks:
      - well
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - STORE_MODE=db
      - SEATA_PORT=8091

  # seata:
  #   image: seataio/seata-server:1.6.1
  #   hostname: seata_standalone
  #   container_name: seata_standalone
  #   networks:
  #     - well
  #   environment:
  #     - STORE_MODE=db
  #     - SEATA_IP=192.168.220.230
  #     - SEATA_PORT=8091
  #   volumes:
  #     - ./config/resources/application.yml:/seata-server/resources/application.yml
  #     - ./data/sessionStore:/seata-server/sessionStore
  #     - ./data/logs:/root/logs/seata
  #   ports:
  #     - "8091:8091"
  #     - "7091:7091"
